import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { UIExample } from '@shared/ui-component'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Customer Web!</a>
        </h1>

        <UIExample text="via @shared using resolver" />
      </main>
    </div>
  )
}
