import Head from 'next/head'
import { useEffect } from 'react'
import styles from '../styles/Home.module.css'
import { UIExample } from '@shared/ui-component'

export default function Home() {

  useEffect(() => {
    if (typeof document !== undefined) {
      require("../../node_modules/@shared/ui-component/dist/ui.bundle.min")
      console.log("document exist")
    }
    else {
      console.log("document not exist")
    }
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Customer Web!</a>
        </h1>

        <UIExample text="via @shared using resolver" />

        <button type="button" className="btn btn-success">Primary</button>
        {/* <Button>
          Click me from shared package
        </Button> */}
      </main>
    </div>
  )
}
