import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Button, MyBadge, Badge } from '@shared/ui-component'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div className='w-100'>
          <div className='d-flex justify-content-end'>
            <MyBadge>
              Custom badge
            </MyBadge>
          </div>
        </div>

        <h1 className='my-4'>
          Welcome to <a href="https://nextjs.org">Customer Web!</a>
        </h1>

        <Button color='primary'>
          Click this shared button
        </Button>
      </main>
    </div>
  )
}
